"""
Derives every logo asset the application needs from src/assets/logo.png.

RUN THIS BY HAND, NOT AS PART OF THE BUILD.

    python scripts/build-logo-assets.py

Its outputs are committed, so `npm run build` and `npm run dist` need neither
Python nor Pillow. Re-run it only when src/assets/logo.png changes.

Outputs
    build/icon.ico          multi-resolution Windows icon (installer, shortcuts,
                            taskbar, packaged window title bar)
    build/icon.png          256px square, for the development window icon
    shared/logo.ts          the same mark as a base64 data URI

WHY A DATA URI RATHER THAN A FILE
    Printed documents are built as self-contained HTML in the main process and
    rendered in an offscreen window (see electron/services/print.service.ts). A
    document that referenced a logo *file* would print with a broken image the
    moment the path resolved differently — which, between `npm run dev`, an asar
    archive and a temp directory, is most of the time. Inlining the bytes means
    the document cannot lose its own logo.

    The same module serves the React screens: one asset, no build-pipeline
    difference between the two processes, and the Content-Security-Policy already
    permits `img-src data:`.
"""

from __future__ import annotations

import base64
import io
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "src" / "assets" / "logo.png"

# Windows shows the 16px entry in Explorer's list view and the 256px one in the
# installer and on the desktop. Everything between is used by some part of the
# shell, and letting Windows downscale for the missing sizes looks noticeably
# worse than shipping them.
ICO_SIZES = [16, 24, 32, 48, 64, 128, 256]

# Enough for a 64px logo on a 200%-scaled display, and for the A4 invoice header
# at print resolution, without carrying the 600 KB source into the bundle.
MARK_SIZE = 256


def squared(image: Image.Image) -> Image.Image:
    """Trims transparent margins, then re-centres the mark in a square.

    The source art is neither tight nor centred — its ink occupies 865x948 of a
    1254x1254 canvas, sitting off to one side. Downscaling that to 16px directly
    would spend most of the icon on empty space and put the mark off-centre.
    """
    bbox = image.getbbox()
    if bbox is None:
        raise SystemExit("logo.png is entirely transparent")

    trimmed = image.crop(bbox)
    side = max(trimmed.size)
    canvas = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    canvas.paste(
        trimmed,
        ((side - trimmed.width) // 2, (side - trimmed.height) // 2),
    )
    return canvas


def with_margin(image: Image.Image, fraction: float) -> Image.Image:
    """Adds breathing room, as Windows icon guidelines expect."""
    side = image.width
    inner = round(side * (1 - fraction * 2))
    canvas = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    scaled = image.resize((inner, inner), Image.Resampling.LANCZOS)
    offset = (side - inner) // 2
    canvas.paste(scaled, (offset, offset))
    return canvas


def png_bytes(image: Image.Image) -> bytes:
    buffer = io.BytesIO()
    image.save(buffer, format="PNG", optimize=True)
    return buffer.getvalue()


def write_ico(image: Image.Image, target: Path) -> None:
    """Writes a multi-resolution ICO, resampling each entry individually.

    Pillow can do this in one call, but resampling each size from the full-
    resolution original rather than from a chain of reductions keeps the small
    entries sharper — which is the only place this logo's fine detail (the
    screwdriver, the antennae) has any chance of surviving.
    """
    frames = [
        image.resize((size, size), Image.Resampling.LANCZOS) for size in ICO_SIZES
    ]
    largest = frames[-1]
    largest.save(
        target,
        format="ICO",
        sizes=[(size, size) for size in ICO_SIZES],
        append_images=frames[:-1],
    )


def write_logo_module(data_uri: str, target: Path) -> None:
    target.write_text(
        f'''/**
 * The shop logo, inlined.
 *
 * GENERATED by scripts/build-logo-assets.py from src/assets/logo.png.
 * Do not edit by hand — re-run that script instead.
 *
 * It is a data URI rather than a file path because printed documents are
 * self-contained HTML rendered in an offscreen window from a temp directory
 * (electron/services/print.service.ts). A relative path would resolve
 * differently in `npm run dev`, inside the asar archive, and at print time, so
 * the invoice would silently print without its logo. Inlined bytes cannot go
 * missing.
 *
 * The React screens import the same constant, so there is one asset and no
 * pipeline difference between the two processes. The Content-Security-Policy in
 * index.html already permits `img-src data:`.
 *
 * {MARK_SIZE}x{MARK_SIZE}, trimmed and centred.
 */

export const LOGO_DATA_URI =
  '{data_uri}';

/** Square, so any box it goes in can be square too. */
export const LOGO_ASPECT = 1;
''',
        encoding="utf-8",
    )


def main() -> None:
    source = Image.open(SOURCE).convert("RGBA")
    mark = squared(source)

    build = ROOT / "build"
    build.mkdir(exist_ok=True)

    # The icon gets a margin; the in-app mark does not, because it is placed in
    # boxes that already have their own padding.
    write_ico(with_margin(mark, 0.04), build / "icon.ico")

    dev_icon = mark.resize((MARK_SIZE, MARK_SIZE), Image.Resampling.LANCZOS)
    (build / "icon.png").write_bytes(png_bytes(dev_icon))

    encoded = base64.b64encode(png_bytes(dev_icon)).decode("ascii")
    write_logo_module(f"data:image/png;base64,{encoded}", ROOT / "shared" / "logo.ts")

    print(f"source        {source.size[0]}x{source.size[1]}")
    print(f"trimmed       {mark.size[0]}x{mark.size[1]} (centred square)")
    print(f"build/icon.ico  {(build / 'icon.ico').stat().st_size:>7,} bytes  {ICO_SIZES}")
    print(f"build/icon.png  {(build / 'icon.png').stat().st_size:>7,} bytes")
    print(f"shared/logo.ts  {(ROOT / 'shared' / 'logo.ts').stat().st_size:>7,} bytes")


if __name__ == "__main__":
    main()
